const NB_ISOLATE = 2;

const ENCRYPTION = 0;
const DECRYPTION = 1;
const INITIALISATION = 2;

const CERT_XCHG_BEGIN = 30;
const CERT_XCHG_END = 31;
const ENCRYPTED_DATA = 32;
const UNENCRYPTED_DATA = 33;
