const POOLING_DISCOVERY = 1000;
const NB_WRAPPERS = 2;

const CONNECT_SERVER = 11;
const CONNECT_CLIENT = 12;
const CONNECT_BROADCAST = 13;
const DISCONNECT_BROADCAST = 14;
const BROADCAST = 15;

const INTERNAL_EXCEPTION = 16;
const CONNECTION_EVENT = 17;
const DISCONNECTION_EVENT = 18;
const DATA_RECEIVED = 19;
const FORWARD_DATA = 20;

const MESSAGE_EVENT = 21;
const BROKEN_LINK = 22;
const DEVICE_INFO_BLE = 23;
const DEVICE_INFO_WIFI = 24;
